# Generated by Django 2.2.4 on 2019-08-21 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
