# Generated by Django 2.2.4 on 2019-08-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(default='helloworld'),
        ),
    ]
