# Generated by Django 2.2.4 on 2019-09-03 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0002_auto_20190902_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden_by',
            field=models.ManyToManyField(related_name='hidden_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
