# Generated by Django 2.2.4 on 2019-09-04 02:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('socialife', '0003_auto_20190903_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='HashTag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='hashtags',
        ),
    ]
