# Generated by Django 2.2.4 on 2019-09-09 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0004_auto_20190904_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
