# Generated by Django 2.2.4 on 2019-08-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0004_auto_20190818_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='slug',
            new_name='profile_name',
        ),
    ]
