# Generated by Django 2.2.4 on 2019-08-23 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0005_auto_20190823_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
