# Generated by Django 2.2.4 on 2019-08-20 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0005_auto_20190819_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='followings',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
