# Generated by Django 2.2.4 on 2019-08-25 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0006_chatroom_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='notice_by_users',
            field=models.ManyToManyField(related_name='chat_room_noticed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by_users',
            field=models.ManyToManyField(related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
