# Generated by Django 2.2.4 on 2019-08-26 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0007_auto_20190825_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_interaction',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
