# Generated by Django 2.2.4 on 2019-08-26 14:03

from django.db import migrations, models
import socialife.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0008_chatroom_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default-avatar.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
    ]
