# Generated by Django 2.2.4 on 2019-08-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0009_auto_20190826_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.URLField(default='https://i.ibb.co/vxKKNwk/tt-avatar-small.jpg'),
        ),
    ]
