# Generated by Django 2.2.4 on 2019-08-27 08:39

from django.db import migrations, models
import socialife.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0010_auto_20190827_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default-avatar.png', upload_to=socialife.models.MyUser.user_directory_path),
        ),
    ]
