# Generated by Django 2.2.4 on 2019-08-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0011_auto_20190827_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='channel_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
