# Generated by Django 2.2.4 on 2019-08-29 11:42

from django.db import migrations, models
import django.db.models.deletion
import socialife.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialife', '0012_myuser_channel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=socialife.models.PostImage.user_directory_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='socialife.Post')),
            ],
        ),
    ]
